version: '2'
volumes:
  firmware:
services:
  platform:
    build: ./platform
    privileged: true
    volumes:
      - '/mnt/data/resin-data/firmware/frontend:/usr/src/app'
    depends_on:
      - frontend
      - services
  services:
    build: ./services
    privileged: true
    volumes:
      - '/mnt/data/resin-data/firmware/app:/usr/src/app'
  frontend:
    build: ./frontend
    privileged: true
    volumes:
      - '/mnt/data/resin-data/firmware/app:/usr/src/app'

