version: '2'
volumes:
  firmware:
services:

  platform:
    build: ./platform
    privileged: true
    labels:
      io.resin.features.kernel-modules: '1'
    depends_on:
      - services

  services:
    build: ./services
    privileged: true

  frontend:
    build: ./frontend
    privileged: true
    depends_on:
      - platform
    volumes:
      - 'firmware:/usr/src/app'

