version: '2'
volumes:
  firmware:
services:

  platform:
    build: ./platform
    privileged: true
    depends_on:
      - services

  services:
    build: ./services
    privileged: true

  frontend:
    build: ./frontend
    privileged: true
    depends_on:
      - platform
    volumes:
      - 'firmware:/usr/src/app'

