version: '2'
volumes:
  ui:
services:
  platform:
    build: ./platform
    privileged: true
    volumes:
      - 'ui/frontend:/usr/src/app'
    depends_on:
      - frontend
      - services
  services:
    build: ./services
    privileged: true
    volumes:
      - 'ui/app:/usr/src/app'
  frontend:
    build: ./frontend
    privileged: true
    volumes:
      - 'ui/app:/usr/src/app'

