version: '2'
volumes:
  firmware:
services:
  platform:
    build: ./platform
    privileged: true
    volumes:
      - firmware/frontend:/usr/src/app
    depends_on:
      - frontend
      - services
  services:
    build: ./services
    privileged: true
    volumes:
      - firmware/app:/usr/src/app
  frontend:
    build: ./frontend
    privileged: true
    volumes:
      - firmware/app:/usr/src/app

