FROM resin/%%RESIN_MACHINE_NAME%%-node:8

# Install other apt deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  apt-utils \
  python-dev \
  python-pip \
  python-smbus

RUN pip install evdev \
  && pip install RPi.GPIO

WORKDIR /usr/bin

COPY ./hyperpixel-init .
COPY ./hyperpixel-touch .

WORKDIR /usr/src/app

COPY ./start.sh .

CMD ["bash", "/usr/src/app/start.sh"]



